### ISSUE TITLE
Make a QR Code with an empty zone in the middle

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [whomwah/rqrcode_core#38]
Hello !

Is it possible to be able to leave an empty zone in the middle of the QR Code ?

This is in order to be able to insert an image inside, like this :
![image](https://github.com/whomwah/rqrcode_core/assets/6117264/77dfcac2-33df-4e99-88e7-225a0481ad80)

I am not very familiar with the algo of QR Code, so if it is not possible, I would also appreciate if you could point the places in the code where I could go to implement that in a fork.

Thanks !

**Comment by swifthand** [comment]
@JeSuisUnCaillou I do not know if @whomwah wishes to support this or not, but as background information, you should be aware that this is not officially supported in the latest [ISO 18004:2015 Standard for QR Codes](https://gcore.jsdelivr.net/gh/tonycrane/tonycrane.github.io/p/409d352d/ISO_IEC18004-2015.pdf). 

Of course people still produce these anyway.  
The way this is most often achieved is by relying on the QR Code's built-in error correction level (referred to as "L", "M", "Q" and "H"--you will want to use "H"). You intentionally block part of a valid code, effectively damaging it, but do so _carefully_, in a way that you keeps the payload data readable the majority of the time because of this high error correction setting. How easy this is can change depending on your data and settings. You may need to manually experiment with the number of modules that are blocked, relative to the amount of data in the payload (something which results in a setting called the "version"). 

You have to be careful. It will make your code more difficult to scan, and possibly fail entirely. You will want to be conservative in how many modules you block, and to test on many, many codes that are representative of your data.

I recommend [reading this tutorial](https://www.thonky.com/qr-code-tutorial/). Once you have, you will understand the tradeoffs of the "error correction level" and "version" that you make when you damage a QR code with an image overlay, but still keep it readable.

**A little history:**
For many years, the company that created QR Codes (DENSO WAVE) specifically _warned against_ doing this. Eventually DENSO WAVE released a product (and a trademark term "FrameQR") that has this feature, but it is not officially part of the ISO Standard.

**The future?**
There is supposed to be [an update to the standard next month](https://www.iso.org/standard/83389.html), but I do not know whether this will or will not include a standardized "FrameQR" option.

**Comment by whomwah** [comment]
As @swifthand alludes too, this is not something the library will support. You're free to just abuse the error correction though and just add an image like most of these kind of qrcodes do in the wild.

**Comment by JeSuisUnCaillou** [comment]
Thanks for the info, that's precious :+1: 

I kinda understood the same thing by myself after a while, but it's nice to have a confirmation (About abusing the error correction to place an image in the middle).

I ended up going another route, by developing [this gem](https://github.com/JeSuisUnCaillou/visual-qrcode/) based on rqrcode_core, to have a sort of "background image" which I think can look pretty nice with a logo :

![image](https://github.com/JeSuisUnCaillou/visual-qrcode/raw/main/spec/images/marianne_visual_qrcode.png)
